ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from .sitemaps import StaticViewSitemap, ProductViewSitemap
from django.contrib.sitemaps.views import sitemap
from . import views
from os import getenv

sitemaps = {
    'static': StaticViewSitemap,
    'product': ProductViewSitemap,
}

urlpatterns = [
    path(getenv('ADMIN_URL'), admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path('robots.txt', views.robots),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",
)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('', include('shop.urls')),
    path('customer/', include('customer.urls')),
    path('payment/', include('payment.urls')),
)

shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product-list'),
    path('products/<int:pk>/<str:slug>/', views.product_detail, name='product-detail'),
    path('review/<int:pk>/', views.review, name='review'),
    path('api/', include('shop.api.urls'))
]

templates/includes/nav-categories.html
{% load cache %}

{% cache 3600 nav-categories %}
<div class="navbar-nav w-100">
    {% for general_category in general_categories %}
        <div class="nav-item dropdown dropright">
            <span class="nav-link dropdown-toggle" data-toggle="dropdown">{{general_category.title}}<i class="fa fa-angle-right float-right mt-1"></i></span>
            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                {% for category in general_category.sub_categories.all %}
                    <a href="{% url 'shop:product-list' %}?categories={{category.pk}}" class="dropdown-item">{{category.title}}</a>
                {% endfor %}
               
            </div>
        </div>
    {% endfor %}
    {% for category in pure_categories %}
        <a href="{% url 'shop:product-list' %}?categories={{category.pk}}" class="nav-item nav-link">{{category.title}}</a>
    {% endfor %}
    
</div>

{% endcache %}

templates/includes/product-cart.html
{% load shop_helper %}
{% load customer_helper %}


<div class="{% firstof custom_class 'col-lg-3 col-md-4 col-sm-6 pb-1' %}">
    <div class="product-item bg-light mb-4">
        <div class="product-img position-relative overflow-hidden">
            <img class="img-fluid w-100" style="height: 400px; object-fit: cover; object-position: top;" src="{{product.images.first.image.url}}" alt="{{product.title}}">
            <div class="product-action">
                <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
            {% if not product|is_wished:request %}
                <span class="btn btn-outline-dark btn-square wish-button wished" product-id="{{product.pk}}"><i class="far fa-heart"></i></span>
                {% else %}
                <span class="btn btn-outline-dark btn-square wish-button nonwished" product-id="{{product.pk}}"><i class="fas fa-heart"></i></span>
            {% endif %}
                <a class="btn btn-outline-dark btn-square" href="{{product.get_absolute_url}}"><i class="fa fa-search"></i></a>
            </div>
        </div>
        <div class="text-center py-4">
            <a class="h6 text-decoration-none text-truncate" href="{{product.get_absolute_url}}">{{product.title}}</a>
            <div class="d-flex align-items-center justify-content-center mt-2">
                {% if product.old_price %}
                    <h5>{% get_price_text request product.price %}</h5><h6 class="text-muted ml-2"><del>{% get_price_text request product.old_price %}</del></h6>
                {% else %}
                    <h5>{% get_price_text request product.price %}</h5>
                {% endif %}
            </div>
            <div class="d-flex align-items-center justify-content-center mb-1">
                {% stars product.get_avg_star %}
                <small>({{product.reviews.all.count}})</small>
            </div>
        </div>
    </div>
</div>

templates/includes/stars.html
{% for _ in full_stars %}
    <small class="fa fa-star text-primary mr-1"></small>
{% endfor %}

{% if half_star %}
    <small class="fa fa-star-half-alt text-primary mr-1"></small>
{% endif %}

{% for _ in empty_stars %}
    <small class="far fa-star text-primary mr-1"></small>
{% endfor %}