customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('basket/', views.basket, name='basket'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('wish-product/<int:pk>', views.wish_products, name='wish-product'),
    path('unwish-product/<int:pk>', views.unwish_products, name='unwish-product'),
    path('add-basket/<int:product_pk>/', views.add_basket, name='add-basket'),
    path('increase-basket-item/<int:basket_pk>', views.increase_basket_item, name='increase-basket-item'),
    path('decrease-basket-item/<int:basket_pk>', views.decrease_basket_item, name='decrease-basket-item'),
    path('remove-basket/<int:basket_pk>/', views.remove_basket, name='remove-basket'),
    path('change-currency/', views.change_currency, name='change-currency'),
    path('forgot-password/', views.forgot_password_view, name='forgot-password'),
    path('reset-password/<str:token>/', views.reset_password_view, name='reset-password'),
    path('reset-password-result/<str:color>/<str:message>/', views.reset_password_result_view, name='reset-password-result')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from .sitemaps import StaticViewSitemap, ProductViewSitemap
from django.contrib.sitemaps.views import sitemap
from . import views
from os import getenv

sitemaps = {
    'static': StaticViewSitemap,
    'product': ProductViewSitemap,
}

urlpatterns = [
    path(getenv('ADMIN_URL'), admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path('robots.txt', views.robots),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",
)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('', include('shop.urls')),
    path('customer/', include('customer.urls')),
    path('payment/', include('payment.urls')),
)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout')
]

shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product-list'),
    path('products/<int:pk>/<str:slug>/', views.product_detail, name='product-detail'),
    path('review/<int:pk>/', views.review, name='review'),
    path('api/', include('shop.api.urls'))
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from uuid import uuid4
from django.utils.timezone import localtime, timedelta
from django.urls import reverse
from secrets import token_urlsafe

# Create your models here.


class WishItem(models.Model):
    product = models.ForeignKey('shop.Products', on_delete=models.CASCADE)
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE, related_name='wishlist')
    created = models.DateTimeField(auto_now_add=True)

class BasketItem(models.Model):
    product = models.ForeignKey('shop.Products', on_delete=models.CASCADE)
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE, related_name='basketlist')
    count = models.IntegerField(default=0)
    size = models.ForeignKey('shop.Size', on_delete=models.CASCADE)
    color = models.ForeignKey('shop.Color', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')

    def __str__(self):
        return self.user.username

class Review(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='reviews')
    product = models.ForeignKey('shop.Products', on_delete=models.CASCADE, related_name='reviews')
    comment = models.TextField()
    star_count = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created = models.DateField(auto_now_add=True)


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
    



class ResetPassword(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    token = models.CharField(max_length=100)
    used = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.token = self.token or token_urlsafe(50)
        print('SHOW')
        return super().save(*args, **kwargs)

    def is_valid(self):
        not_used = not self.used
        not_expired = (localtime() - timedelta(days=1)) < self.created
        return not_used and not_expired
    
    def get_absolute_url(self):
        return reverse("customer:reset-password", kwargs={"token": self.token})
    

customer/forms.py
from django import forms
from .models import Contact, Customer, ResetPassword
from django.contrib.auth.models import User

class ContactForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        model = Contact
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Email'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Message', 'rows': '8'}),
        }

class RegisterForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password_again = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'}))


    def save(self):
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        email = self.cleaned_data['email']
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        user = User.objects.create_user(
            first_name=first_name,
            last_name=last_name,
            email=email,
            username=username,
            password=password,
        )

        customer = Customer.objects.create(user=user)
        
        return customer
    



class PasswordResetForm(forms.Form):
    token = forms.CharField(widget=forms.HiddenInput())
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password_again = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'}))


    def clean(self):
        cleaned_data = super().clean()
        token = cleaned_data['token']
        username = cleaned_data['username']
        password = cleaned_data['password']
        password_again = cleaned_data['password_again']
        rp = ResetPassword.objects.filter(token=token).first()
        user = User.objects.filter(username=username).first()
        if not user:
            raise forms.ValidationError('User not found')
        if not rp or rp.user != user:
            raise forms.ValidationError('Process failed')
        
        if password and password_again and password != password_again:
            raise forms.ValidationError('Passwords do not match')
        
        return cleaned_data
    

    def save(self):
        cleaned_data = self.cleaned_data
        username = cleaned_data['username']
        password = cleaned_data['password']
        user = User.objects.get(username=username)
        user.set_password(password)
        user.save()
        rp = ResetPassword.objects.get(token=cleaned_data['token'])
        rp.used = True
        rp.save()
        return user

customer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ContactForm, RegisterForm, PasswordResetForm
from shop.models import Products
from .models import WishItem, BasketItem, ResetPassword
from payment.models import Coupon
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, F
from django.conf import settings
from django.core.mail import send_mail

# Create your views here.


def contact(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contact.html', {'form': form, 'result': 'success'})
        return render(request, 'contact.html', {'form': form, 'result': 'fail'})
    return render(request, 'contact.html', {'form': form})

@login_required
def wishlist_view(request):
    wishlist = request.user.customer.wishlist.all()
    total_price = wishlist.aggregate(total_price = Sum('product__price'))['total_price']
    # Author.objects.annotate(total_pages=Sum("book__pages"))
    return render(request, 'wishlist.html', {'wishlist': wishlist, 'total_price': total_price,})

@login_required
def wish_products(request, pk):
    product = get_object_or_404(Products, pk=pk)
    customer = request.user.customer
    WishItem.objects.create(product=product, customer=customer)
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
def unwish_products(request, pk):
    product = get_object_or_404(Products, pk=pk)
    customer = request.user.customer
    WishItem.objects.filter(product=product, customer=customer).delete()
    return redirect(request.META.get('HTTP_REFERER'))

@login_required
def basket(request):
    basketlist = request.user.customer.basketlist.all().annotate(total_price=F('count') * F('product__price'))
    all_price = basketlist.aggregate(all_price=Sum('total_price'))['all_price'] or 0
    shipping_price = all_price * 0.1
    final_price = all_price + shipping_price


    coupon_code = request.GET.get('coupon', '')
    coupon_message = None
    coupon_status = None
    coupon_discount = 0
    coupon_discount_amount = 0
    if coupon_code:
        coupon = Coupon.objects.filter(code=coupon_code).first()
        if coupon:
            is_valid, message = coupon.is_valid(request.user.customer)
            if is_valid:
                coupon_status = 'valid'
                coupon_message = message
                coupon_discount = coupon.discount
                coupon_discount_amount = final_price * coupon_discount / 100
                final_price -= coupon_discount_amount
            else:
                coupon_status = 'invalid'
                coupon_message = message
        else:
            coupon_status = 'invalid'
            coupon_message = 'Bele bir kod yoxdur'


    return render(request, 'basket.html', {
        'basketlist' : basketlist,
        'all_price' : round(all_price, 2),
        'shipping_price' : round(shipping_price, 2),
        'final_price' : round(final_price, 2),
        'coupon_code' : coupon_code,
        'coupon_message' : coupon_message,
        'coupon_status' : coupon_status,
        'coupon_discount' : coupon_discount,
        'coupon_discount_amount' : round(coupon_discount_amount, 2),
    })

@login_required
def add_basket(request, product_pk):
    if request.method == 'POST':
        size_pk = request.POST.get('size')
        color_pk = request.POST.get('color')
        count = request.POST.get('count')
        customer = request.user.customer
        basket = BasketItem.objects.create(product_id=product_pk, size_id=size_pk, color_id=color_pk, count=count, customer=customer)
        return redirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect('shop:home')
    
@login_required
def increase_basket_item(request, basket_pk):
    basket = get_object_or_404(BasketItem, pk=basket_pk)
    basket.count = F('count') + 1
    basket.save()
    return redirect('customer:basket')

@login_required
def decrease_basket_item(request, basket_pk):
    basket = get_object_or_404(BasketItem, pk=basket_pk)
    if basket.count == 1:
        basket.delete()
    else:
        basket.count = F('count') - 1
        basket.save()
    return redirect('customer:basket')

@login_required
def remove_basket(request, basket_pk):
    basket = get_object_or_404(BasketItem, pk=basket_pk)
    basket.delete()
    return redirect('customer:basket')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        remember = request.POST.get('remember', False)
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            if not remember:
                request.session.set_expiry(0)
            return redirect('shop:home')
        return render(request, 'login.html', {'fail': True})
    return render(request, 'login.html', {'fail': False})

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            print('duzdu')
            customer = form.save()
            login(request, customer.user)
            return redirect('shop:home')
        print('salam')
    return render(request, 'register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('customer:login')


usd_eq = {'AZN' : 1.7, 'TRY': 21, 'EUR': 0.93, 'USD': 1}
def change_currency(request):
    currency = request.GET.get('currency')
    currency_ratio = usd_eq[currency]
    request.session['currency'] = currency
    request.session['currency_ratio'] = currency_ratio
    return redirect(request.META.get('HTTP_REFERER'))


def forgot_password_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.filter(email=email).first()
        if user:
            ResetPassword.objects.filter(user=user).update(used=True)
            rp = ResetPassword.objects.create(user=user)
            url = request.build_absolute_uri(rp.get_absolute_url())
            message = f'Please renew your password from this link: {url}'
            subject = 'Renew your password'
            sender = settings.EMAIL_HOST_USER
            send_mail(subject, message, sender, [email])
            return redirect('customer:reset-password-result', color='success', message='Mail sent successfully')
        else:
            return render(request, 'forgot_password.html', {'status': 'invalid_user'})
    
    return render(request, 'forgot_password.html')

def reset_password_view(request, token):
    rp = ResetPassword.objects.filter(token=token).first()
    if rp and rp.is_valid():
        if request.method == 'GET':
            form = PasswordResetForm(initial={'token': token})
            return render(request, 'reset-password.html', {'form': form})
        else:
            form = PasswordResetForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('customer:reset-password-result', color='success', message='Password changed successfully')
            return render(request, 'reset-password.html', {'form': form})
    else:
        return redirect('customer:reset-password-result', color='danger', message='The reset password link is invalid or expired')

    

def reset_password_result_view(request, color, message):
    return render(request, 'reset-password-result.html', {'color': color, 'message': message})

customer/templates/basket.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    <title>{% trans "Basket" %}</title>
{% endblock title %}

{% block main %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">{% trans "Home" %}</a>
                    <a class="breadcrumb-item text-dark" href="#">{% trans "Shop" %}</a>
                    <span class="breadcrumb-item active">{% trans "Shopping Cart" %}</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>{% trans "Products" %}</th>
                            <th>{% trans "Price" %}</th>
                            <th>{% trans "Quantity" %}</th>
                            <th>{% trans "Total" %}</th>
                            <th>{% trans "Remove" %}</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for basket in basketlist %}
                            <tr>
                                <td class="align-middle"><img src="{{basket.product.images.first.image.url}}" alt="" style="width: 50px;">{{basket.product.title}}</td>
                                <td class="align-middle">${{basket.product.price}}</td>
                                <td class="align-middle">
                                    <div class="input-group quantity mx-auto" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <a href={% url 'customer:decrease-basket-item' basket_pk=basket.pk %} class="btn btn-sm btn-primary btn-minus" >
                                            <i class="fa fa-minus"></i>
                                            </a>
                                        </div>
                                        <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="{{basket.count}}">
                                        <div class="input-group-btn">
                                            <a href={% url 'customer:increase-basket-item' basket_pk=basket.pk %} class="btn btn-sm btn-primary btn-plus">
                                                <i class="fa fa-plus"></i>
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle">${{basket.total_price|floatformat:1}}</td>
                                <td class="align-middle"><a href="{% url 'customer:remove-basket' basket_pk=basket.pk %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" method="GET">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" name="coupon" value="{{coupon_code}}" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">{% trans "Apply Coupon" %}</button>
                        </div>
                    </div>
                    {% if coupon_status == 'valid' %}
                        <p class="text-success font-weight-bold">{{coupon_message}}</p>
                    {% elif coupon_status == 'invalid' %}
                        <p class="text-danger font-weight-bold">{{coupon_message}}</p>
                    {% endif %}
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">{% trans "Cart Summary" %}</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>{% trans "Subtotal" %}</h6>
                            <h6>${{all_price|floatformat:2}}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">{% trans "Shipping" %}</h6>
                            <h6 class="font-weight-medium">${{shipping_price|floatformat:2}}</h6>
                        </div>
                        {% if coupon_status == 'valid' %}
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium">{% trans "Discount" %}</h6>
                                <h6 class="font-weight-medium">- ${{coupon_discount_amount}} ({{coupon_discount}}%)</h6>
                            </div>
                        {% endif %}
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>{% trans "Total" %}</h5>
                            <h5>${{final_price|floatformat:2}}</h5>
                        </div>
                        {% if final_price %}
                            <a href="{% url 'payment:checkout' %}{% if coupon_status == 'valid' %}?coupon={{coupon_code}}{% endif %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock main %}

customer/templates/contact.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    <title>{% trans "Contact" %}</title>
{% endblock title %}

{% block main %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">{% trans "Home" %}</a>
                    <span class="breadcrumb-item active">{% trans "Contact" %}</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Contact Start -->
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">{% trans "Contact Us" %}</span></h2>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form bg-light p-30">
                    {% if result == 'success' %}
                        <div class="alert alert-success" role="alert">
                            {% trans "Müraciətiniz uğurla göndərildi!" %}
                        </div>
                    {% elif result == 'fail' %}
                        <div class="alert alert-danger" role="alert">
                            {% trans "Uğursuz əməliyyat!" %}
                        </div>
                    {% endif %}
                    <p class="text-danger">{{form.non_field_error}}</p>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="control-group mb-2">
                            {{form.name}}
                            {% for error in form.name.errors %}
                                <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div class="control-group mb-2">
                            {{form.email}}
                            {% for error in form.email.errors %}
                                <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div class="control-group mb-2">
                            {{form.subject}}
                            {% for error in form.subject.errors %}
                                <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div class="control-group mb-2">
                            {{form.message}}
                            {% for error in form.message.errors %}
                                <p class="text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">{% trans "Send Message" %}</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <div class="bg-light p-30 mb-30">
                    <iframe style="width: 100%; height: 250px;"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                    frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
                <div class="bg-light p-30 mb-3">
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>{% trans "123 Street, New York, USA" %}</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock main %}

customer/templates/login.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    <title>Login</title>
{% endblock title %}

{% block main %}
    <div class="container">
        <div class="form-wrapper row p-5">
            <div class="col-6 offset-3 bg-warning p-4">
                <div class="display-3 text-dark text-center pb-4 font-weight-bold">Login</div>
                {% if fail %}
                    <div class="alert alert-danger" role="alert">
                        İstifadəçi adı və ya şifrə yanlışdır!
                    </div>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="control-group">
                        <input type="text" class="form-control" placeholder="Username"
                            required="required" name="username"/>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="password" class="form-control" placeholder="Password"
                            required="required" name="password" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="row">
                        <div class="control-group col-6">
                            <input id="remember" type="checkbox" name="remember" value="off">
                            <label for="remember">{% trans "Remember Me" %}</label>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{% url 'customer:forgot-password' %}" class="text-dark">Forgot Password</a>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-dark py-2 px-4" type="submit" id="sendMessageButton">
                            Login
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock main %}

customer/templates/wishlist.html
{% extends 'layout.html' %}
{% load static %}
{% load shop_helper %}

{% block title %}
    <title>Wishlist</title>
{% endblock title %}

{% block main %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <a class="breadcrumb-item text-dark" href="#">Shop</a>
                    <span class="breadcrumb-item active">Whishlist</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-12 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for wishitem in wishlist %}
                            <tr>
                                <td class="align-middle"><img src="{{wishitem.product.images.first.image.url}}" alt="" style="width: 50px;"> <a href="{{wishitem.product.get_absolute_url}}" class="text-dark">{{wishitem.product.title}}</a></td>
                                <td class="align-middle">${{wishitem.product.price}}</td>
                                <td class="align-middle">
                                    {% stars wishitem.product.get_avg_star %}
                                </td>
                                <td class="align-middle"><a class="btn btn-sm btn-danger" href="{% url 'customer:unwish-product' pk=wishitem.product.pk %}"><i class="fa fa-times"></i></a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock main %}